"""initial schema

Revision ID: 3968b0a9534e
Revises: 
Create Date: 2026-10-06 14:40:40.573594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3968b0a9534e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_saves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=40), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_saves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_saves_player_name'), ['player_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_saves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_saves_player_name'))

    op.drop_table('game_saves')
    # ### end Alembic commands ###
